### PR TITLE
Create Composer script to generate fixtures

### PR DESCRIPTION
**Pull request by tedbow**
Just to make easier to update python dependencies and create fixtures

### CODE REVIEW

**Review by phenaproxima — CHANGES_REQUESTED** [review]
To make sure it works, can you also modify our CI configuration so that it invokes this command, rather than calling `pipenv` directly?

Also: I don't think we actually need to call `pipenv update`, because if I'm reading the Pipfile correctly, all of our dependencies are locked to specific versions anyway.

**Review by tedbow — COMMENTED** [review]
Great idea!

**Comment by phenaproxima** [comment]
😂 It was _your_ idea, @tedbow!

**Review by phenaproxima — APPROVED** [review]
Approved after manual test by @tedbow.

**Pull request merged**
