### PR TITLE
Add known security vulnerabilities check on CI

### PR DESCRIPTION
**Pull request by TravisCarden**
This adds a check for dependencies for known security vulnerabilities to CI builds.

### CODE REVIEW

**Review by phenaproxima — APPROVED** [review]
No objections, but I'd like @tedbow to cross-check before we merge this.

**Comment by phenaproxima** [comment]
Since Composer now has an `audit` command, we should probably use that instead.

**Review by phenaproxima — CHANGES_REQUESTED** [review]
Could we use `composer audit` for this instead?

**Comment by TravisCarden** [comment]
Sure, @phenaproxima! Let's just do what we did in https://github.com/php-tuf/composer-integration/pull/62.

**Pull request merged**
