### PR TITLE
Add stub for meeting minutes to the repository

### PR DESCRIPTION
**Pull request by xjm**

### CODE REVIEW

**Comment by davidstrauss** [comment]
Could we track these outside of the main git repo, possibly? What do you think of using the GitHub wiki functionality, which also stores in git (but not the code git repo)?

**Review by davidstrauss — CHANGES_REQUESTED** [review]
Could we track these outside of the main git repo, possibly? What do you think of using the GitHub wiki functionality, which also stores in git (but not the code git repo)?

**Review by hestenet — APPROVED** [review]

**Comment by hestenet** [comment]
> Could we track these outside of the main git repo, possibly? What do you think of using the GitHub wiki functionality, which also stores in git (but not the code git repo)?

Actually - this is probably a better idea! I'm going to play around with that.

**Comment by hestenet** [comment]
Yeah, the wiki will work well, so I'm going to close this PR

Work will continue here: https://github.com/php-tuf/php-tuf/wiki

**Comment by xjm** [comment]
Works for me. I added a link to the wiki to the README as well. (I know it's in a tab, but still better for the README to be the central starting point for all docs IMO).

**Pull request closed without merging**
