### PR TITLE
Support non-seekable streams in SizeCheckingLoader

### LINKED ISSUE #169: Handle non-seekable streams in Updater:: checkLength()
Coming at you from #153!

There's an outstanding @todo at https://github.com/php-tuf/php-tuf/blob/main/src/Client/Updater.php#L535 which states:

```
        if (isset($size)) {
            if ($size > $maxBytes) {
                throw $error;
            }
        } else {
            // @todo Handle non-seekable streams.
            $data->rewind();
            $data->read($maxBytes);
```

Seems like a good thing to do. :)

### PR DESCRIPTION
**Pull request by phenaproxima**
Fixes #169.

### CODE REVIEW

**Comment by phenaproxima** [comment]
Due to the fact that this intentionally introduces side effects, I think I'm going to want sign-off from both @tedbow and @effulgentsia before this is merged.

**Review by tedbow — APPROVED** [review]
Looks good!

**Comment by phenaproxima** [comment]
I confirmed that the changes here un-break the tests in php-tuf/composer-integration.

**Comment by phenaproxima** [comment]
Welp, since this blocks the plugin, I'm mergin' this.

**Pull request merged**
