### PR TITLE
Ensure metadata factory methods return signature Verified metadata

### PR DESCRIPTION
**Pull request by tedbow**
Currently we have a few spots that do something like

`$newTimestampData = TimestampMetadata::createFromJson($newTimestampContents);
  $this->checkSignatures($newTimestampData);`

It's good to `checkSignatures()` before we interact more with the data. If we moved the verification into `createFromJson()` then we could ensure that they return verified metadata.

### CODE REVIEW

**Comment by davidstrauss** [comment]
I'm a little confused. The comment here suggests this PR is an alternative to #88 (now merged), but most of the diff seems to be refactoring. Is there a better high-level description of what I should be looking for in this review other than commenting on the design changes in the refactoring?

**Comment by tedbow** [comment]
@davidstrauss yep updated the comment

**Review by davidstrauss — APPROVED** [review]
These changes look good to me, though I'm not intimately familiar with the current architecture of the PHP. I like what appears to be dependency injection for the signature verification.

**Comment by tedbow** [comment]
Not sure if this need any more. I do like the idea of having a `SignatureVerifier`

**Comment by tedbow** [comment]
Closing this in favor of #198

**Pull request closed without merging**
