### PR TITLE
Create test for attacks with new fixtures

### PR DESCRIPTION
**Pull request by tedbow**

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Very cool! How did you generate the JSON for the attacks? Using `generate.py`?

**Comment by tedbow** [comment]
> How did you generate the JSON for the attacks? Using `generate.py`?
@trishankatdatadog yes. This is my first python so it may be a bit rough 😂

**Comment by trishankatdatadog** [comment]
Would you mind upstreaming your PR to theupdateframework/tuf generate the attack fixtures?

**Comment by tedbow** [comment]
@trishankatdatadog sure I can do that

**Comment by tedbow** [comment]
Closing this PR. I open a more specific #101 one.

I am not sure we can create fixtures that simulate all types of attack but we should be able to simulate rollback attacks at least. We can have separate PRs different types of attacks

**Pull request closed without merging**
